stages:
  train:
    cmd: python make_pipeline.py --config configs/train_config.yaml
    deps:
      - configs/train_config.yaml
      - data/raw/
    outs:
      - models/metrics.json
      - models/catclf.pkl