channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=23.1.2
- pip:
  - mlflow==2.12.1
  - catboost==1.2.3
  - cloudpickle==3.0.0
  - numpy==1.23.1
  - packaging==21.3
  - pandas==1.4.3
  - pyyaml==6.0
  - scikit-learn==1.1.1
  - scipy==1.8.1
name: mlflow-env
